import { Chat } from "@/context/ChatContext";
import { config } from "./config";

export const mockChats: Chat[] = [
  {
    id: 1,
    name: "Note to Self",
    lastMessage: "Buy groceries and pick up dry cleaning",
    timestamp: "2m ago",
    unreadCount: 0,
    avatar: "📝",
    isOnline: true,
    username: config.username,
    unreadMessages: [
      {
        id: 1,
        text: "Don't forget to call the plumber",
        timestamp: "2025-01-01T12:00:00Z",
        isMe: true,
        type: "text",
      },
      {
        id: 2,
        text: "Also, remember to water the plants",
        timestamp: "2025-01-01T12:05:00Z",
        isMe: true,
        type: "text",
      },
    ],
  },
  {
    id: 2,
    name: "Sarah Wilson",
    lastMessage: "Can we meet tomorrow?",
    timestamp: "5m ago",
    unreadCount: 0,
    avatar: "👩‍🎨",
    isOnline: true,
    username: "",
    unreadMessages: [
      {
        id: 1,
        text: "Sure, what time works for you?",
        timestamp: "2025-01-01T12:10:00Z",
        isMe: false,
        type: "text",
      },
      {
        id: 2,
        text: "How about 3 PM?",
        timestamp: "2025-01-01T12:15:00Z",
        isMe: false,
        type: "text",
      },
    ],
  },
  {
    id: 4,
    name: "Mom",
    lastMessage: "Don't forget dinner at 7pm",
    timestamp: "2h ago",
    unreadCount: 0,
    avatar: "👩‍🦳",
    isOnline: false,
    username: "",
    unreadMessages: [
      {
        id: 1,
        text: "Also, bring the dessert!",
        timestamp: "2025-01-01T11:00:00Z",
        isMe: false,
        type: "text",
      },
    ],
  },
  {
    id: 5,
    name: "Alex Johnson",
    lastMessage: "Thanks for the help!",
    timestamp: "1d ago",
    unreadCount: 0,
    avatar: "👨‍💻",
    isOnline: false,
    username: "",
    unreadMessages: [
      {
        id: 1,
        text: "I really appreciate your support on the project.",
        timestamp: "2025-01-01T10:00:00Z",
        isMe: false,
        type: "text",
      },
      {
        id: 2,
        text: "Let's catch up next week!",
        timestamp: "2025-01-01T10:05:00Z",
        isMe: false,
        type: "text",
      },
    ],
  },
  {
    id: 6,
    name: "Emma Davis",
    lastMessage: "See you at the party 🎉",
    timestamp: "2d ago",
    unreadCount: 0,
    avatar: "👩‍🦰",
    isOnline: true,
    username: "",
    unreadMessages: [
      {
        id: 1,
        text: "Can't wait! It's going to be so much fun.",
        timestamp: "2025-01-01T09:00:00Z",
        isMe: false,
        type: "text",
      },
      {
        id: 2,
        text: "I'll bring the drinks!",
        timestamp: "2025-01-01T09:05:00Z",
        isMe: false,
        type: "text",
      },
    ],
  },
];
