name: Block non-dev merges to main

on:
  pull_request:
    branches: [main]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is not dev
        if: github.head_ref != 'dev'
        run: |
          echo "Only dev branch can be merged into main"
          exit 1
